// Define the jobs for building VM images for CI.
pipeline {
    agent { label "fedora3 || fedora32" }

    options {
        timestamps()
        ansiColor('xterm')
    }

    triggers {
        cron 'H 5 * * 1-5'
    }


    stages {

        stage("PSI Images") {
            // Set the agent here in this stage so run all of the builds in
            // the same agent.
            environment {
                OPENSTACK_CLOUDS_YAML = credentials("psi-openstack-clouds-yaml")
            }
            steps {
                sh "schutzbot/packer_install.sh"
            }
        }

        stage("Build images") {

            // Build the images in parallel.
            parallel {

                stage("Fedora 31") {
                    steps {
                        sh "packer.io build openstack/fedora31.json"
                    }
                }

                stage("Fedora 32") {
                    steps {
                        sh "packer.io build openstack/fedora32.json"
                    }
                }

                stage("RHEL 8.2") {
                    steps {
                        sh "packer.io build openstack/rhel82.json"
                    }
                }

                stage("RHEL 8.3") {
                    steps {
                        sh "packer.io build openstack/rhel83.json"
                    }
                }

            }

            post {
                always {
                    // Always clean up credentials.
                    sh "sudo rm -rf /etc/openstack"
                }
            }
        }
    }
}
