pipeline {
    agent none

    options {
        timestamps()
        ansiColor('xterm')
    }

    stages {

        stage("PSI Images") {
            agent { label "fedora3 || fedora32" }
            stage("Install packer") {
                steps {
                    sh "schutzbot/packer_install.sh"
                }
            }
            stage("Build images")
                parallel {
                    stage("Fedora 31") {
                        steps {
                            sh "packer build openstack/fedora31.json"
                        }
                    }
                    stage("Fedora 32") {
                        steps {
                            sh "packer build openstack/fedora31.json"
                        }
                    }
                }
            }
        }
    }
}
