pipeline {
    agent { label "fedora3 || fedora32" }

    options {
        timestamps()
        ansiColor('xterm')
    }

    stages {

        stage("PSI Images") {
            // Set the agent here in this stage so run all of the builds in
            // the same agent.
            steps {
                sh "schutzbot/packer_install.sh"
            }
        }

        stage("Build images") {

            // Build the images in parallel.
            parallel {

                stage("Fedora 31") {
                    steps {
                        sh "packer.io build openstack/fedora31.json"
                    }
                }

                stage("Fedora 32") {
                    steps {
                        sh "packer.io build openstack/fedora31.json"
                    }
                }

            }
        }
    }
}
